import 'package:flutter_salam/Common/task_model.dart';

class AllTasksLogic {
  List<TaskModel> tasks = [
    TaskModel(
      hours: "٥",
      name: "مهمة ٢٠",
      desc: "مهمة ٢٠ Description ",
      type: "Type 9",
      location: "Location 15",
      timeStamp: DateTime.now(),
      startTime: DateTime.now(),
      endTime: DateTime.now().add(Duration(days: 10)),
      createdById: "2",
      acceptedById: null,
      isSpecialized: true,
      specialization: "Specialization 2",
    ),
    TaskModel(
      hours: "٢",
      name: "مهمة ٢١",
      desc: "مهمة ٢١ Description ",
      type: "Type 1",
      location: "Location 1",
      timeStamp: DateTime.now(),
      startTime: DateTime.now(),
      endTime: DateTime.now().add(Duration(days: 20)),
      createdById: "3",
      acceptedById: null,
      isSpecialized: true,
      specialization: "Specialization 2",
    ),
    TaskModel(
      hours: "١٠",
      name: "مهمة ٥٥",
      desc: "مهمة ٥٥ Description ",
      type: "Type 12",
      location: "Location 55",
      timeStamp: DateTime.now(),
      startTime: DateTime.now(),
      endTime: DateTime.now().add(Duration(days: 19)),
      createdById: "4",
      acceptedById: null,
      isSpecialized: true,
      specialization: "Specialization 5",
    ),
    TaskModel(
      hours: "١",
      name: "مهمة ٦٦",
      desc: "مهمة ٦٦ Description ",
      type: "Type 66",
      location: "Location 66",
      timeStamp: DateTime.now(),
      startTime: DateTime.now(),
      endTime: DateTime.now().add(Duration(days: 5)),
      createdById: "5",
      acceptedById: null,
      isSpecialized: true,
      specialization: "Specialization 6",
    ),
    TaskModel(
      hours: "٨",
      name: "مهمة ٧٧",
      desc: "مهمة ٧٧ Description ",
      type: "Type 77",
      location: "Location 77",
      timeStamp: DateTime.now(),
      startTime: DateTime.now(),
      endTime: DateTime.now().add(Duration(days: 12)),
      createdById: "2",
      acceptedById: null,
      isSpecialized: true,
      specialization: "Specialization 7",
    ),
    TaskModel(
      hours: "٣",
      name: "مهمة ٥٥",
      desc: "مهمة ٥٥ Description ",
      type: "Type 10",
      location: "Location 6",
      timeStamp: DateTime.now(),
      startTime: DateTime.now(),
      endTime: DateTime.now().add(Duration(days: 5)),
      createdById: "3",
      acceptedById: null,
      isSpecialized: true,
      specialization: "Specialization 5",
    ),
  ];
}
